Bdtss level generation
Foxtezy/DeadInByte pull request #9
Opened 2022-11-05 06:49 UTC by BuDum-Tss

2022-11-05 06:59 UTC, Foxtezy commented on src/main/resources/assets/levels/texture_pallettes/new_palette.json
> +  "Platform": 130,
А этот json зачем нужен?

2022-11-05 07:09 UTC, Foxtezy requested changes

2022-11-05 07:09 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
Мне всё не нравится, что ты здесь level наследуешь

2022-11-05 07:09 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
Его лучше в конструкторе передать и вынести как поле

2022-11-05 07:09 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
И через это поле обращаться к level

2022-11-05 07:09 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
https://javarush.ru/groups/posts/1967-otnoshenija-mezhdu-klassami-nasledovanie-kompozicija-i-agregirovanie-

2022-11-05 07:09 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
Получается у нас должна быть композиция (просто сейчас у нас генератор является уровнем)

2022-11-05 07:13 UTC, Foxtezy commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/Way/FindWay.java
> +  int width;
ты тут модификаторы доступа забыла

2022-11-05 07:17 UTC, Foxtezy commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Ещё восстанови все файлы которые ты удалилв

2022-11-05 07:17 UTC, Foxtezy commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Хотя я и сам могу

2022-11-05 07:29 UTC, BuDum-Tss commented on src/main/resources/assets/levels/texture_pallettes/new_palette.json
> +  "Platform": 130,
Это в будущем для преобразования карты в tmx

2022-11-05 07:31 UTC, BuDum-Tss commented on src/main/java/ru/nsu/fit/dib/projectdib/level_generation/GenerationMethods/BinaryPartition/BinaryPartitionLG.java
> +public class BinaryPartitionLG extends Level {
Окк

2022-11-05 08:06 UTC, BuDum-Tss commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Что за файлы

2022-11-05 08:07 UTC, BuDum-Tss commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Из за их отсутствия на билдится?

2022-11-05 08:07 UTC, BuDum-Tss commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Оккк

2022-11-05 08:20 UTC, Foxtezy commented on .mvn/wrapper/maven-wrapper.properties
> -distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip
Да

2022-11-13 09:03 UTC, Foxtezy approved these changes

2022-11-13 09:03 UTC, merged